config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wings
  resources :patients
  resources :records
  resources :welcomes
  root to: "wings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caretaker.rb
class Caretaker < ApplicationRecord
  has_many :caretaker_placements
  has_many :records, through: :caretaker_placements
  has_many :patients, through: :records

  validates :first_name, :last_name, :title, presence: true
  
  before_save :titleize

  def titleize
    self.first_name = self.first_name.titleize
    self.last_name = self.last_name.titleize
  end
  
  def name
    first_name + ' ' + last_name
  end
end

app/models/caretaker_placement.rb
class CaretakerPlacement < ApplicationRecord
  belongs_to :record
  belongs_to :caretaker
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :patient_placements
  has_many :wings, through: :patient_placements
  has_many :records

  validates :first_name, :last_name, :sex, :age, presence: true
  
  before_save :titleize

  def titleize 
    self.first_name = self.first_name.titleize
    self.last_name = self.last_name.titleize 
  end

  def name
    first_name + ' ' + last_name
  end
end

app/models/patient_placement.rb
class PatientPlacement < ApplicationRecord
  belongs_to :patient
  belongs_to :wing
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :caretaker_placements
  has_many :caretakers, through: :caretaker_placements
  belongs_to :patient

  validates :patient_id, :description, :admitted_at, presence: true
end

app/models/wing.rb
class Wing < ApplicationRecord
  has_many :patient_placements
  has_many :patients, through: :patient_placements

  validates :name, :description, presence: true

  before_save :titleize

  def titleize 
    self.name = self.name.titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index; end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index; end
end

app/controllers/wings_controller.rb
class WingsController < ApplicationController
  def index
    @wings = Wing.all
  end

  def show
    @wing = Wing.find(params[:id])
  end

  private
  def wing_params
    params.require(:wing).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_dependency.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeneralShospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render "layouts/dependency" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="container-fluid shadow-health-logo">
  <%= link_to wings_path do %>
    <%= image_tag 'logo.png', class: 'shadow-health-logo-size' %>
  <% end %>
</div>

app/views/welcomes/index.html.erb
<%= render 'shared/header' %>
<div id="welcomehero">

  <div class="w-25 m-auto px-5 py-4 welcome-content">
    <p>
      <strong>Welcome</strong> to Shadow Health General Shospital.
      You will get to know our departments, patients and doctors all at once.
    </p>
    <%= link_to wings_path, class: 'to-dep float-right' do %>
      Continue
    <% end %>
  </div>

  <%= image_tag 'Diana-Leader-smiling.png', width:'300px', height:'600px',class: 'diana' %>

</div>

app/views/wings/_wing.html.erb
<tr height="30"></tr>
<tr class="row row-color">
  <td class="col-11 dep-c font-weight-bold p-4">
    <%= wing.name %>
  </td>
  <td class="col-1 p-4">
    <%= link_to wing_path(wing), class: 'dep-next' do %>
      <i class="material-icons dep-c">label_important</i>
    <% end %>
  </td>
</tr>

app/views/wings/index.html.erb
<%= render 'shared/header' %>
<div id="winghero">
  <h1>OUR DEPARTMENTS</h1>
  <br/>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    <br/>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  </p>
</div>
<%= link_to welcomes_path, class: 'help-icon' do %>
  <i class="material-icons question question-icon animated bounce delay-2s">help_outline</i>
<% end %>
<br/>
<br/>
<div class="mb-5">
  <div class="w-75 m-auto px-5 py-4 board-content">
    <table class="container">
      <%= render @wings if @wings.any? %>
    </table>
  </div>
</div>

app/views/wings/show.html.erb
<%= render 'shared/header' %>
<div id="patienthero">

  <div class="w-75 m-auto px-5 py-4 patient-content">
    <h1><%= @wing.name %></h1>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <span style="color:#5b9a93">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit</span>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
  </div>

</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<div>
<h1 class="patients">Patients</h1>
<br/>
  <div class="row m-5">
    <% @wing.patients.each do |patient| %>
      <div class="col-sm-4">
        <a data-toggle="collapse" href="#patientRecord<%=patient.id%>" role="button" aria-expanded="false" aria-controls="patientRecord<%=patient.id%>">
          <div class="card patient-card mb-3">
            
            <%= image_tag 'https://i.ibb.co/BVjXZrr/user.png', class: 'patient-icon ml-2 mr-2 mt-2 mx-auto d-block' %>
            
            <div class="card-body body-space">
              <h2 class="card-title text-center patients"><%= patient.name %></h2>
            </div>
          </div>
        </a>
        <div class="collapse" id="patientRecord<%=patient.id%>">
          <div class="card card-body">
           <p><%=patient.first_name%> <%=patient.last_name%>, <%=patient.age%>, <%=patient.sex%><br/>Conditions:<br/>bvjbnouhfodnfo.</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>